/*
   Copyright 2012 Ruben Serrano, Joan Fuentes

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
package org.uab.deic.uabdroid.services;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

/**
 * 
 * BroadcastReceiver which listens for the two broadcast events generated by an UABDroid alarm
 * 
 * @author Ruben Serrano
 *
 */

public class UABDroidReceiver extends BroadcastReceiver 
{
	public static final String UPDATE_INTENT = "org.uab.deic.uabdroid.UPDATE_INTENT";
	public static final String ALARM_INTENT = "org.uab.deic.uabdroid.ALARM_INTENT";
	
	@Override
	public void onReceive(Context context, Intent intent) 
	{
		if (intent.getAction().equalsIgnoreCase(UPDATE_INTENT))
		{
			Intent startIntent = new Intent(context, UpdateService.class);
			context.startService(startIntent);
		}
		else if (intent.getAction().equalsIgnoreCase(ALARM_INTENT))
		{
			Intent startIntent = new Intent(context, AlarmService.class);
			context.startService(startIntent);
		}
	}

}
